name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.ADMIN_REPO_TOKEN }}
          reviewers: |
            /coders
          addAssignees: false
