name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "Assign reviewers from team"
        uses: dc-ag/auto-assign-reviewers-from-team@v1.2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          team: "coders" # The team name
          use-team-reviewer-settings: true # Set to true if you want to use the team's reviewer settings instead of a specific amount
